language: ruby
cache: bundler
rvm:
  - 2.1.5
before_install: gem install bundler -v 1.10.6

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      amodut@gmail.com
    on_failure: change
    on_success: never